name: Build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Build with Gradle
      run: |
        ./gradlew build
        cp /home/runner/work/forecastie/forecastie/app/build/outputs/apk/release/app-release-unsigned.apk /home/runner/work/forecastie/forecastie/forecastie.apk
        pwd > file_list.txt
        ls -lR >> file_list.txt

    - name: Upload .apk
      uses: actions/upload-artifact@v4
      with:
        name: Forecastie
        path: forecastie.apk

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: /github/workspace/forecastie.apk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Download
      #uses: actions/download-artifact@v1
      #id: download
      #with:
        #name: 'Forecastie'
        #path: ./build/
